// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: public/projects/api.proto

package projects

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManualBuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *ManualBuildRequest) Reset() {
	*x = ManualBuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_projects_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManualBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualBuildRequest) ProtoMessage() {}

func (x *ManualBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_projects_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualBuildRequest.ProtoReflect.Descriptor instead.
func (*ManualBuildRequest) Descriptor() ([]byte, []int) {
	return file_public_projects_api_proto_rawDescGZIP(), []int{0}
}

func (x *ManualBuildRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ManualBuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *ManualBuildResponse) Reset() {
	*x = ManualBuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_projects_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManualBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualBuildResponse) ProtoMessage() {}

func (x *ManualBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_projects_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualBuildResponse.ProtoReflect.Descriptor instead.
func (*ManualBuildResponse) Descriptor() ([]byte, []int) {
	return file_public_projects_api_proto_rawDescGZIP(), []int{1}
}

func (x *ManualBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string          `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Args      []*TargetArg    `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Secrets   []*TargetSecret `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_projects_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_public_projects_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_public_projects_api_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Target) GetArgs() []*TargetArg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Target) GetSecrets() []*TargetSecret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type TargetArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TargetArg) Reset() {
	*x = TargetArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_projects_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetArg) ProtoMessage() {}

func (x *TargetArg) ProtoReflect() protoreflect.Message {
	mi := &file_public_projects_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetArg.ProtoReflect.Descriptor instead.
func (*TargetArg) Descriptor() ([]byte, []int) {
	return file_public_projects_api_proto_rawDescGZIP(), []int{3}
}

func (x *TargetArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetArg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TargetSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TargetSecret) Reset() {
	*x = TargetSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_projects_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSecret) ProtoMessage() {}

func (x *TargetSecret) ProtoReflect() protoreflect.Message {
	mi := &file_public_projects_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSecret.ProtoReflect.Descriptor instead.
func (*TargetSecret) Descriptor() ([]byte, []int) {
	return file_public_projects_api_proto_rawDescGZIP(), []int{4}
}

func (x *TargetSecret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetSecret) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_public_projects_api_proto protoreflect.FileDescriptor

var file_public_projects_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x22, 0x4b, 0x0a, 0x12, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x30, 0x0a,
	0x13, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22,
	0x97, 0x01, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x3b, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x09, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x38, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_projects_api_proto_rawDescOnce sync.Once
	file_public_projects_api_proto_rawDescData = file_public_projects_api_proto_rawDesc
)

func file_public_projects_api_proto_rawDescGZIP() []byte {
	file_public_projects_api_proto_rawDescOnce.Do(func() {
		file_public_projects_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_projects_api_proto_rawDescData)
	})
	return file_public_projects_api_proto_rawDescData
}

var file_public_projects_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_public_projects_api_proto_goTypes = []interface{}{
	(*ManualBuildRequest)(nil),  // 0: api.public.projects.ManualBuildRequest
	(*ManualBuildResponse)(nil), // 1: api.public.projects.ManualBuildResponse
	(*Target)(nil),              // 2: api.public.projects.Target
	(*TargetArg)(nil),           // 3: api.public.projects.TargetArg
	(*TargetSecret)(nil),        // 4: api.public.projects.TargetSecret
}
var file_public_projects_api_proto_depIdxs = []int32{
	2, // 0: api.public.projects.ManualBuildRequest.targets:type_name -> api.public.projects.Target
	3, // 1: api.public.projects.Target.args:type_name -> api.public.projects.TargetArg
	4, // 2: api.public.projects.Target.secrets:type_name -> api.public.projects.TargetSecret
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_public_projects_api_proto_init() }
func file_public_projects_api_proto_init() {
	if File_public_projects_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_projects_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManualBuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_projects_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManualBuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_projects_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_projects_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_projects_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_projects_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_projects_api_proto_goTypes,
		DependencyIndexes: file_public_projects_api_proto_depIdxs,
		MessageInfos:      file_public_projects_api_proto_msgTypes,
	}.Build()
	File_public_projects_api_proto = out.File
	file_public_projects_api_proto_rawDesc = nil
	file_public_projects_api_proto_goTypes = nil
	file_public_projects_api_proto_depIdxs = nil
}
