// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: skeleton.proto

package skeleton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoItRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoItRequest) Reset() {
	*x = DoItRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skeleton_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoItRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoItRequest) ProtoMessage() {}

func (x *DoItRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skeleton_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoItRequest.ProtoReflect.Descriptor instead.
func (*DoItRequest) Descriptor() ([]byte, []int) {
	return file_skeleton_proto_rawDescGZIP(), []int{0}
}

type DoItResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoItResponse) Reset() {
	*x = DoItResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skeleton_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoItResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoItResponse) ProtoMessage() {}

func (x *DoItResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skeleton_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoItResponse.ProtoReflect.Descriptor instead.
func (*DoItResponse) Descriptor() ([]byte, []int) {
	return file_skeleton_proto_rawDescGZIP(), []int{1}
}

var File_skeleton_proto protoreflect.FileDescriptor

var file_skeleton_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x73, 0x6b, 0x65,
	0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x6f, 0x49, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x6f, 0x49, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x59, 0x0a, 0x08, 0x53, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e,
	0x12, 0x4d, 0x0a, 0x04, 0x44, 0x6f, 0x49, 0x74, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x44,
	0x6f, 0x49, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e,
	0x2e, 0x44, 0x6f, 0x49, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_skeleton_proto_rawDescOnce sync.Once
	file_skeleton_proto_rawDescData = file_skeleton_proto_rawDesc
)

func file_skeleton_proto_rawDescGZIP() []byte {
	file_skeleton_proto_rawDescOnce.Do(func() {
		file_skeleton_proto_rawDescData = protoimpl.X.CompressGZIP(file_skeleton_proto_rawDescData)
	})
	return file_skeleton_proto_rawDescData
}

var file_skeleton_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_skeleton_proto_goTypes = []interface{}{
	(*DoItRequest)(nil),  // 0: api.public.skeleton.DoItRequest
	(*DoItResponse)(nil), // 1: api.public.skeleton.DoItResponse
}
var file_skeleton_proto_depIdxs = []int32{
	0, // 0: api.public.skeleton.Skeleton.DoIt:input_type -> api.public.skeleton.DoItRequest
	1, // 1: api.public.skeleton.Skeleton.DoIt:output_type -> api.public.skeleton.DoItResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skeleton_proto_init() }
func file_skeleton_proto_init() {
	if File_skeleton_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_skeleton_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoItRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skeleton_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoItResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skeleton_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skeleton_proto_goTypes,
		DependencyIndexes: file_skeleton_proto_depIdxs,
		MessageInfos:      file_skeleton_proto_msgTypes,
	}.Build()
	File_skeleton_proto = out.File
	file_skeleton_proto_rawDesc = nil
	file_skeleton_proto_goTypes = nil
	file_skeleton_proto_depIdxs = nil
}
