// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: skeleton.proto

package skeleton

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SkeletonService_DoIt_FullMethodName = "/api.public.skeleton.v1.SkeletonService/DoIt"
)

// SkeletonServiceClient is the client API for SkeletonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkeletonServiceClient interface {
	DoIt(ctx context.Context, in *DoItRequest, opts ...grpc.CallOption) (*DoItResponse, error)
}

type skeletonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkeletonServiceClient(cc grpc.ClientConnInterface) SkeletonServiceClient {
	return &skeletonServiceClient{cc}
}

func (c *skeletonServiceClient) DoIt(ctx context.Context, in *DoItRequest, opts ...grpc.CallOption) (*DoItResponse, error) {
	out := new(DoItResponse)
	err := c.cc.Invoke(ctx, SkeletonService_DoIt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkeletonServiceServer is the server API for SkeletonService service.
// All implementations must embed UnimplementedSkeletonServiceServer
// for forward compatibility
type SkeletonServiceServer interface {
	DoIt(context.Context, *DoItRequest) (*DoItResponse, error)
	mustEmbedUnimplementedSkeletonServiceServer()
}

// UnimplementedSkeletonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkeletonServiceServer struct {
}

func (UnimplementedSkeletonServiceServer) DoIt(context.Context, *DoItRequest) (*DoItResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoIt not implemented")
}
func (UnimplementedSkeletonServiceServer) mustEmbedUnimplementedSkeletonServiceServer() {}

// UnsafeSkeletonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkeletonServiceServer will
// result in compilation errors.
type UnsafeSkeletonServiceServer interface {
	mustEmbedUnimplementedSkeletonServiceServer()
}

func RegisterSkeletonServiceServer(s grpc.ServiceRegistrar, srv SkeletonServiceServer) {
	s.RegisterService(&SkeletonService_ServiceDesc, srv)
}

func _SkeletonService_DoIt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoItRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkeletonServiceServer).DoIt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkeletonService_DoIt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkeletonServiceServer).DoIt(ctx, req.(*DoItRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkeletonService_ServiceDesc is the grpc.ServiceDesc for SkeletonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkeletonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.public.skeleton.v1.SkeletonService",
	HandlerType: (*SkeletonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoIt",
			Handler:    _SkeletonService_DoIt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skeleton.proto",
}
